# Generated by Django 4.2.4 on 2023-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYapp', '0002_rename_mobile_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(choices=[('memory', 'memory'), ('portrait', 'portrait'), ('wedding', 'wedding'), ('fashion', 'fashion'), ('travel', 'travel')], max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
