# Generated by Django 4.2.4 on 2023-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYapp', '0005_middleslider_upperslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleslider',
            name='image_category',
            field=models.CharField(blank=True, choices=[('memory', 'memory'), ('portrait', 'portrait'), ('wedding', 'wedding'), ('fashion', 'fashion'), ('travel', 'travel')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='upperslider',
            name='image_category',
            field=models.CharField(blank=True, choices=[('memory', 'memory'), ('portrait', 'portrait'), ('wedding', 'wedding'), ('fashion', 'fashion'), ('travel', 'travel')], max_length=10, null=True),
        ),
    ]
